# Generated by Django 4.2.5 on 2023-10-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidad',
            new_name='unidad_medida',
        ),
    ]
